-- Id 생성 전략을 TSID로 변경
ALTER TABLE users MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE todo MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE sub_todo MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE todo_group MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE icon MODIFY COLUMN id BIGINT NOT NULL;
