name: Auto PR Review

on:
  pull_request:
    types: [opened, synchronize]  # PR이 생성되거나 업데이트될 때 실행

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # PR 변경사항을 가져옴

      - name: Get PR Diff
        run: |
          git fetch origin develop  # 기준 브랜치 가져오기
          git diff origin/develop > pr_diff.txt  # PR과 develop 브랜치의 차이점 저장
          echo "PR diff has been saved to pr_diff.txt"
      
      - name: Analyze PR with GPT-4o
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # pr_diff.txt 파일의 내용을 JSON 문자열로 안전하게 이스케이프
          ESCAPED_DIFF=$(jq -Rs . < pr_diff.txt)
          
          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4o",
              "messages": [
                {"role": "system", "content": "You are an expert software engineer. Review the provided code changes and suggest improvements."},
                {"role": "user", "content": "The following code changes were made:\n'"$ESCAPED_DIFF"'\nPlease review the changes and provide feedback. Answer in Korean."}
              ]
            }')
          
          echo "Full API Response:"
          echo "$RESPONSE"
          
          REVIEW=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
          echo "Extracted Review:"
          echo "$REVIEW"
          echo "$REVIEW" > review_comment.txt
          echo "Code review generated successfully."


      - name: Add Review Comment to PR
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          REVIEW=$(cat review_comment.txt)
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
            -d "{\"body\": \"$REVIEW\"}"
  

